// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzAgND8yXqBvac9QrdcsjvWcQWEEo9iVU',
    appId: '1:929910218798:web:9e83bacb192e912a0dffbf',
    messagingSenderId: '929910218798',
    projectId: 'logistic-app-flutter',
    authDomain: 'logistic-app-flutter.firebaseapp.com',
    storageBucket: 'logistic-app-flutter.appspot.com',
    measurementId: 'G-KD3KCKXT40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4bdDNfm-14NlQ7DWp9QFttRy7fJc-t2I',
    appId: '1:929910218798:android:99952c6e0ad363910dffbf',
    messagingSenderId: '929910218798',
    projectId: 'logistic-app-flutter',
    storageBucket: 'logistic-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDajSZwjo_uCE8FYOL0aNfbycKT0sV2I3Q',
    appId: '1:929910218798:ios:5063d5fa58e99b540dffbf',
    messagingSenderId: '929910218798',
    projectId: 'logistic-app-flutter',
    storageBucket: 'logistic-app-flutter.appspot.com',
    iosBundleId: 'com.example.logisticapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDajSZwjo_uCE8FYOL0aNfbycKT0sV2I3Q',
    appId: '1:929910218798:ios:e7b898be3f657cd50dffbf',
    messagingSenderId: '929910218798',
    projectId: 'logistic-app-flutter',
    storageBucket: 'logistic-app-flutter.appspot.com',
    iosBundleId: 'com.example.logisticapp.RunnerTests',
  );
}
