const String googleApiKey = "AIzaSyCemOhqkOMkdSrz17sSmI0AvyxYQDM93EY";
const String supabaseUrl = "https://uikockdmivtqfcrehmro.supabase.co";
const String supabaseKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpa29ja2RtaXZ0cWZjcmVobXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDk2OTc2MTksImV4cCI6MjAyNTI3MzYxOX0.wmyM8mRKeydysDl_rAXdzgimNNBy1uR0zqBEz046PKA";
